### ISSUE TITLE
Getting DEAD LOCK on restarting the teamcity server.

### ISSUE THREAD

**Issue by nchidipothu** [JeanRev/TeamcityDockerCloudPlugin#18]
Hi,

If we restart the our teamcity server then docker plugin causing DEAD LOCK and any of existing teamcity agent are not connecting with server.

"DockerTaskScheduler" daemon group="main" prio=5 tid=392 nid=392 blocked on jetbrains.buildServer.clouds.server.impl.instances.RunningInstanceTrackerImpl@77319217
   by "TC: 12:08:05 Update cloud instances to agents mapping; 12:08:05 Task started; Scheduled executor 2"
   java.lang.Thread.State: BLOCKED
    at jetbrains.buildServer.clouds.server.impl.instances.RunningInstanceTrackerImpl.agentDisconnected(RunningInstanceTrackerImpl.java)
    at jetbrains.buildServer.clouds.server.impl.instances.RunningInstanceTrackerImpl$1.agentRemoved(RunningInstanceTrackerImpl.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:121)
    at jetbrains.buildServer.serverSide.ServerSideEventDispatcher.superDispatch(ServerSideEventDispatcher.java:2)
    at jetbrains.buildServer.serverSide.ServerSideEventDispatcher$1.run(ServerSideEventDispatcher.java:2)
    at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAs(SecurityContextImpl.java:27)
    at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAsSystem(SecurityContextImpl.java:34)
    at jetbrains.buildServer.serverSide.ServerSideEventDispatcher.dispatch(ServerSideEventDispatcher.java:11)
    at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:68)
    at com.sun.proxy.$Proxy19.agentRemoved(Unknown Source)
    at jetbrains.buildServer.serverSide.impl.AgentPersistenceFacade.removeAgent(AgentPersistenceFacade.java:130)
    at jetbrains.buildServer.serverSide.impl.BuildAgentManagerImpl.removeAgent(BuildAgentManagerImpl.java:308)
    at jetbrains.buildServer.serverSide.impl.auth.SecuredBuildAgentManager.removeAgent(SecuredBuildAgentManager.java:29)
    at run.var.teamcity.cloud.docker.DefaultDockerCloudClient$SyncWithDockerTask.callInternal(DefaultDockerCloudClient.java:668)
    at run.var.teamcity.cloud.docker.DockerTask.call(DockerTask.java:155)
    at run.var.teamcity.cloud.docker.DockerTask.call(DockerTask.java:23)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at run.var.teamcity.cloud.docker.util.WrappedRunnableScheduledFuture.run(WrappedRunnableScheduledFuture.java:55)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

TC: 12:08:05 Update cloud instances to agents mapping; 12:08:05 Task started; Scheduled executor 2" group="main" prio=5 tid=31 nid=31 waiting on java.util.concurrent.locks.ReentrantLock$NonfairSync@587dd331
   by "DockerTaskScheduler"
   java.lang.Thread.State: WAITING
    at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
    at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
    at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
    at run.var.teamcity.cloud.docker.DefaultDockerCloudClient.isInitialized(DefaultDockerCloudClient.java:177)
    at jetbrains.buildServer.clouds.server.impl.CloudInstancesProviderImpl.iterateProfileInstances(CloudInstancesProviderImpl.java:67)
    at jetbrains.buildServer.clouds.server.impl.CloudInstancesProviderImpl.iterateInstances(CloudInstancesProviderImpl.java:56)
    at jetbrains.buildServer.clouds.server.impl.instances.RunningInstanceTrackerImpl.update(RunningInstanceTrackerImpl.java:102)
    at jetbrains.buildServer.clouds.server.impl.instances.RunningInstanceTrackerImpl$1$1.run(RunningInstanceTrackerImpl.java:76)
    at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:74)
    at jetbrains.buildServer.util.ExceptionUtil$1.run(ExceptionUtil.java:41)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

For WORK-AROUND::

we are disbaling docker cloud profiles and then restarting, then Teamcity starting properly.

Can you please help at this.

**Comment by JeanRev** [comment]
Hi Naresh,

Of course, I'll look into it. The server apparently hangs when trying to remove an obsolete agent...

Can you tell me which version of TeamCity you are using on which OS?

**Comment by nchidipothu** [comment]
Hi,

I am using teamcity 10.0.5 on Linux docker host.

**Comment by JeanRev** [comment]
Thank you for the thread dump,  It's been very helpful. There is indeed a race condition that may lead to a dead-lock when interacting with the TC agent manager.

Here is a fix based on version 0.4.0 of the plugin, can you give it a try?
[docker-cloud_0.4.1-SNAPSHOT_f11f306.zip](https://tc.var.run/repository/download/TeamCityDockerCloudPlugin_Hotfix/180:id/docker-cloud_0.4.1-SNAPSHOT_f11f306.zip?guest=1)
